# Generated by Django 3.0.5 on 2023-05-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_auto_20230503_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/profile_pic/CustomerProfilePic/defualt.png', null=True, upload_to='profile_pic/CustomerProfilePic/'),
        ),
    ]
