# Generated by Django 4.2.1 on 2023-05-31 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecom", "0009_alter_customer_id_alter_feedback_id_alter_orders_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name="customer",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="static/profile_pic/CustomerProfilePic/img.png",
                null=True,
                upload_to="profile_pic/CustomerProfilePic/",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(to="ecom.category"),
        ),
    ]
