# Generated by Django 3.0.5 on 2023-06-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_auto_20230617_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/CustomerProfilePic/default.png', null=True, upload_to='profile_pic/CustomerProfilePic/'),
        ),
    ]
