"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')
STATIC_DIR = os.path.join(BASE_DIR, 'static')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#vw(03o=(9kbvg!&2d5i!2$_58x@_-3l4wujpow6(ym37jxnza'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.fpn-smi.all-as.tech']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ecom',
    'widget_tweaks',
    'social_django',
    'paypal.standard.ipn',
    'chatbot',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR, ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
# Define the URL prefix that will be used to access your static files.

STATIC_URL = '/static/'
# Define the directories where your project will look for static files.

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'static')
# settings.py

# Define the directory where your static files will be collected.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

LOGIN_REDIRECT_URL = '/afterlogin'

# for contact us give your gmail id and password
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'from@gmail.com'  # this email will be used to send emails
EMAIL_HOST_PASSWORD = 'xyz'  # host email password required
# now sign in with your host gmail account in your browser
# open following link and turn it ON
# https://myaccount.google.com/lesssecureapps
# otherwise you will get SMTPAuthenticationError at /contactus
# this process is required because google blocks apps authentication by default
EMAIL_RECEIVING_USER = ['to@gmail.com']  # email on which you will receive messages sent from website

AUTHENTICATION_BACKENDS = [
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]

###the following lines goes in star 158 kola blssa khawya kt3mr blcode lit7tha:
GOOGLE_OAUTH2_CLIENT_ID = '998682705880-92kplb4t1v6jdd1s9tac8m2smj0v11rj.apps.googleusercontent.com'
# 998682705880-92kplb4t1v6jdd1s9tac8m2smj0v11rj.apps.googleusercontent.com
GOOGLE_OAUTH2_CLIENT_SECRET = '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'
# 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
GOOGLE_OAUTH2_REDIRECT_URI = 'http://127.0.0.1/customer_login/callback/'

##the following lines goes in star 166 kola blssa khawya kt3mr blcode lit7tha:

PAYPAL_CLIENT_ID = 'AaqkScVUqRzQKL-v1P5eJfE6TxagBv4cvouFNROdDnuf3ZwuQcIR-jwkeFMa0KVuuv8nweDQta-1jS5x'
# AaqkScVUqRzQKL-v1P5eJfE6TxagBv4cvouFNROdDnuf3ZwuQcIR-jwkeFMa0KVuuv8nweDQta-1jS5x
PAYPAL_CLIENT_SECRET = 'EFCg-p0WUwNPvBL6rEbgAVZqnITWPT62koD_0HSs6GlYfIrXcJQdvhyTQOwiKvNumsUKHc_Z9kN2XUnZ'
# EFCg-p0WUwNPvBL6rEbgAVZqnITWPT62koD_0HSs6GlYfIrXcJQdvhyTQOwiKvNumsUKHc_Z9kN2XUnZ


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

PAYPAL_RECEIVER_EMAIL = 'sananonyme@mail.com'

PAYPAL_TEST = True

PAYPAL_MODE = 'sandbox'  # 'sandbox' or 'live'
